### ISSUE TITLE
eval monitor not working correctly

### ISSUE THREAD

**Issue by Peppershade** [rajnandan1/kener#48]
**Describe the bug**
Docs unclear or app not working as intended. I'm not getting the eval monitor to work

**To Reproduce**
Copy just the eval monitor from the docs, paste it in an empty monitor config.

**Expected behavior**
A working monitor

**Additional context**
On latest release. I tried everything with the syntax, without any luck.

`Kener is running on port 3000!
undefined:1
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at eval (eval at Startup (file:///app/scripts/startup.js:114:32), <anonymous>:2:19)
    at eval (eval at Startup (file:///app/scripts/startup.js:114:32), <anonymous>:12:1)
    at Startup (file:///app/scripts/startup.js:114:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by rajnandan1** [comment]
This is resolved
